### ISSUE TITLE
issame list variable and bin file

### ISSUE THREAD

**Issue by aryachiranjeev** [fdbtrs/ElasticFace#8]
Hi, 
Can you please tell : 
1. What is "issame_list" while loading pickle file
code Line in load_bin function in verification.py:   bins, issame_list = pickle.load(f, encoding='bytes')  # py3

2. And where can I find : alternative: **The evaluation datasets are available in the training dataset package as bin file** ?

Thank you

**Comment by fdbtrs** [comment]
1. Issame list is genuine and imposter pairs
2. Evaluation datasets as bin files can be downloaded from https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_
MS1MV2 dataset
