### ISSUE TITLE
dataset as .bin

### ISSUE THREAD

**Issue by dlwnsgud8406** [fdbtrs/ElasticFace#9]
- I'm not good at English -

1. I downloaded megaface train dataset at https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_ 

but it is not .jpg, it is .bin

I want to know the dataset flow, but I can't read .bin .

How can I read the dataset flow ?? please help me

**Comment by HamDan1999** [comment]
Hi @dlwnsgud8406 
Kindly refer to *Beforehand Data Prepare* section in https://github.com/leondgarse/Keras_insightface to prepare .bin datasets (convert .bin to a folder of .jpgimages ).
